version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Admin123.?"
            ACCEPT_EULA: "Y"
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"
            CONNECTION_STRING: "Server=db;Database=NTier;User=sa;Password=Admin123.?;"
